import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronRight, Move3d, Plus } from "lucide-react";
import { Link } from "wouter";
import ModelViewer from "@/components/ModelViewer";
import ProductCard from "@/components/ProductCard";
import { CartDrawer, Header } from "@/components/StoreChrome";
import { useStore } from "@/contexts/StoreContext";

export default function Home() {
  const { products, addToCart } = useStore();
  const [cartOpen, setCartOpen] = useState(false);
  const [activeFeature, setActiveFeature] = useState(0);
  const features = ["LIGHT", "FORM", "COMFORT", "DETAIL"];
  const featureCopy = ["Reduced visual and physical weight.", "A silhouette designed around natural movement.", "Built for long everyday wear.", "Every element considered."];

  useEffect(() => {
    const timer = window.setInterval(() => setActiveFeature((current) => (current + 1) % features.length), 2800);
    return () => window.clearInterval(timer);
  }, [features.length]);

  return <div className="bg-[#EAE8E1] text-[#111211] selection:bg-[#D7F54A] selection:text-[#111211]">
    <Header onCart={() => setCartOpen(true)} />
    <main>
      {/* Hero */}
      <section className="relative min-h-[760px] overflow-hidden bg-[#111211] text-[#EAE8E1] lg:h-screen lg:min-h-[720px]">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_48%,rgba(79,87,72,0.18),transparent_38%)]" />
        <div className="absolute left-[8%] top-[26%] h-px w-[27%] bg-white/10" /><div className="absolute bottom-[16%] right-[10%] h-px w-[18%] bg-white/10" />
        <div className="relative mx-auto flex min-h-[760px] max-w-[1440px] flex-col justify-between px-5 pb-8 pt-28 sm:px-8 lg:h-full lg:min-h-0 lg:px-12 lg:pb-10 lg:pt-32">
          <div className="grid flex-1 grid-cols-1 lg:grid-cols-[0.76fr_1.24fr]">
            <div className="relative z-10 flex max-w-[520px] flex-col justify-center pb-10 lg:pb-20"><p className="mb-7 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#D7F54A]"><span className="h-px w-10 bg-[#D7F54A]" />01 / APEX SERIES</p><h1 className="font-display text-[clamp(4.8rem,10vw,9.5rem)] font-semibold leading-[0.79] tracking-[-0.08em]"><span className="tracking-[-0.1em]">LYWΛRO</span><br /><span className="text-[#D7F54A]">APEX</span></h1><p className="mt-9 max-w-[300px] font-display text-lg leading-snug text-white/72">Engineered to move.</p><p className="mt-4 max-w-[340px] text-sm leading-6 text-white/45">Precision-built footwear designed for movement, comfort, and everyday performance.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => addToCart(products[0])} className="group inline-flex items-center gap-5 bg-[#D7F54A] px-5 py-3.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#111211] transition hover:bg-[#EAE8E1]">Shop Apex <ArrowUpRight size={14} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button><a href="#apex-story" className="inline-flex items-center gap-2 border border-white/20 px-5 py-3.5 font-mono text-[10px] uppercase tracking-[0.18em] text-white/70 transition hover:border-[#D7F54A] hover:text-[#D7F54A]">Explore details <ArrowDown size={13} /></a></div></div>
            <div className="relative -mx-3 min-h-[390px] lg:mx-0 lg:min-h-0"><ModelViewer className="absolute inset-0" /><div className="pointer-events-none absolute left-[4%] top-[10%] font-mono text-[9px] uppercase tracking-[0.17em] text-white/40 lg:left-[10%] lg:top-[18%]">01 / PERFORMANCE</div><div className="pointer-events-none absolute right-[4%] top-[26%] font-mono text-[9px] uppercase tracking-[0.17em] text-white/40 lg:right-[3%] lg:top-[28%]">02 / LIGHTWEIGHT</div><div className="pointer-events-none absolute bottom-[18%] left-[9%] font-mono text-[9px] uppercase tracking-[0.17em] text-white/40">03 / EVERYDAY</div><div className="pointer-events-none absolute bottom-[24%] right-[7%] flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.17em] text-[#D7F54A]"><span className="h-1.5 w-1.5 rounded-full bg-[#D7F54A]" />Interactive object</div></div>
          </div>
          <div className="flex items-end justify-between border-t border-white/10 pt-5"><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-white/35">Drag to rotate · Scroll to zoom</p><a href="#collection" className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.18em] text-white/55 transition hover:text-[#D7F54A]">Scroll to explore <ArrowDown size={14} /></a><p className="hidden font-mono text-[9px] uppercase tracking-[0.2em] text-white/35 sm:block">Designed in motion / 2026</p></div>
        </div>
      </section>

      {/* Collection */}
      <section id="collection" className="relative overflow-hidden px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]"><div className="mb-16 grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#111211]/45">02 / The collection</p></div><div className="flex items-end justify-between gap-6"><div><h2 className="font-display text-5xl font-semibold leading-[0.92] tracking-[-0.05em] sm:text-7xl">The Apex<br /><span className="text-[#111211]/40">collection.</span></h2><p className="mt-6 max-w-[360px] text-sm leading-6 text-[#111211]/55">Built around movement. Designed around you. Four silhouettes, one considered point of view.</p></div><Link href="/shop" className="hidden items-center gap-2 border-b border-[#111211]/35 pb-2 font-mono text-[10px] uppercase tracking-[0.17em] sm:flex">View all <ArrowUpRight size={13} /></Link></div></div><div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <ProductCard key={product._id || product.id} product={product} />)}</div><Link href="/shop" className="mt-12 flex items-center justify-center gap-2 border border-[#111211]/20 py-4 font-mono text-[10px] uppercase tracking-[0.18em] sm:hidden">View all products <ArrowRight size={13} /></Link></div></section>

      {/* Apex Story — editorial image replaced with gradient */}
      <section id="apex-story" className="bg-[#111211] px-5 py-20 text-[#EAE8E1] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[1.18fr_0.82fr] lg:items-center"><div className="relative min-h-[520px] overflow-hidden border border-white/10 bg-[#181B18]">
        {/* Editorial image placeholder — gradient + texture */}
        <div className="absolute inset-0 bg-gradient-to-br from-[#2a2d2a] via-[#1a1d1a] to-[#0a0d0a]" />
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(255,255,255,0.03) 2px, rgba(255,255,255,0.03) 4px)" }} />
        <div className="absolute inset-0 bg-[#111211]/35" />
        <div className="absolute left-6 top-6 font-mono text-[10px] uppercase tracking-[0.2em] text-white/50">Object study / 01</div>
        <div className="absolute bottom-6 left-6 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.17em] text-[#D7F54A]"><Move3d size={14} />Apex in 3D</div>
        {/* Sneaker silhouette placeholder */}
        <div className="absolute inset-0 flex items-center justify-center opacity-10">
          <div className="h-48 w-72 -rotate-12 rounded-[40%] bg-gradient-to-br from-[#D7F54A]/30 to-transparent shadow-[20px_15px_0_rgba(255,255,255,0.05)]" />
        </div>
      </div><div className="lg:pl-10"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#D7F54A]">03 / Product language</p><h2 className="mt-7 font-display text-5xl font-semibold leading-[0.9] tracking-[-0.05em] sm:text-7xl">Built for<br />motion.</h2><p className="mt-8 max-w-[360px] text-sm leading-7 text-white/50">APEX is a considered, everyday silhouette. Its character lives in the balance: a quiet upper, a responsive base, and just enough edge to make the object unmistakable.</p><ul className="mt-10 space-y-4 border-t border-white/10 pt-5">{["Lightweight construction", "Responsive cushioning", "Breathable upper", "Everyday performance"].map((item) => <li key={item} className="flex items-center gap-3 border-b border-white/10 pb-4 font-mono text-[10px] uppercase tracking-[0.12em] text-white/65"><Check size={13} className="text-[#D7F54A]" />{item}</li>)}</ul><Link href={`/product/${products[0]?.slug || products[0]?._id || "apex"}`} className="mt-9 inline-flex items-center gap-3 bg-[#EAE8E1] px-5 py-3.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#111211] transition hover:bg-[#D7F54A]">View product <ArrowUpRight size={14} /></Link></div></div></div></section>

      {/* Category cards */}
      <section className="bg-[#D8D6CE] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.55fr_1.45fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#111211]/55">04 / Find your motion</p><p className="mt-8 max-w-[180px] font-display text-xl leading-tight">One collection.<br />Different velocities.</p></div><div className="grid gap-px bg-[#111211]/20 sm:grid-cols-3">
        {/* Run card */}
        <Link href="/shop" className="group relative min-h-[320px] overflow-hidden bg-[#EAE8E1] p-6 transition hover:bg-[#111211] hover:text-[#EAE8E1]"><div className="absolute inset-0 bg-gradient-to-br from-[#3a3d3a] to-[#1a1d1a] opacity-0 mix-blend-multiply transition duration-500 group-hover:opacity-35" /><div className="relative flex h-full flex-col justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">01 / Run</span><div><h3 className="font-display text-5xl font-semibold tracking-[-0.06em]">RUN</h3><p className="mt-3 max-w-[190px] text-sm opacity-60">Performance-oriented footwear.</p><span className="mt-8 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em]">Explore <ArrowUpRight size={13} /></span></div></div></Link>
        {/* Move card */}
        <Link href="/shop" className="group relative min-h-[320px] overflow-hidden bg-[#EAE8E1] p-6 transition hover:bg-[#111211] hover:text-[#EAE8E1]"><div className="absolute inset-0 bg-gradient-to-br from-[#b7b3a8]/40 to-[#7c8179]/40 opacity-0 mix-blend-multiply transition duration-500 group-hover:opacity-35" /><div className="relative flex h-full flex-col justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">02 / Move</span><div><h3 className="font-display text-5xl font-semibold tracking-[-0.06em]">MOVE</h3><p className="mt-3 max-w-[190px] text-sm opacity-60">Everyday lifestyle sneakers.</p><span className="mt-8 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em]">Explore <ArrowUpRight size={13} /></span></div></div></Link>
        {/* Form card */}
        <Link href="/shop" className="group relative min-h-[320px] overflow-hidden bg-[#EAE8E1] p-6 transition hover:bg-[#111211] hover:text-[#EAE8E1]"><div className="absolute inset-0 bg-gradient-to-br from-[#4a4d4a] to-[#2a2d2a] opacity-0 mix-blend-multiply transition duration-500 group-hover:opacity-35" /><div className="relative flex h-full flex-col justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em]">03 / Form</span><div><h3 className="font-display text-5xl font-semibold tracking-[-0.06em]">FORM</h3><p className="mt-3 max-w-[190px] text-sm opacity-60">Minimal premium silhouettes.</p><span className="mt-8 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em]">Explore <ArrowUpRight size={13} /></span></div></div></Link>
      </div></div></div></section>

      {/* The Intent */}
      <section className="relative overflow-hidden bg-[#EAE8E1] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="absolute right-0 top-0 h-full w-[36%] bg-[#D8D6CE]" /><div className="relative mx-auto max-w-[1440px]"><div className="grid gap-16 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#111211]/45">05 / The intent</p><h2 className="mt-7 max-w-[540px] font-display text-6xl font-semibold leading-[0.87] tracking-[-0.065em] sm:text-8xl">Designed<br /><span className="text-[#111211]/35">with intent.</span></h2></div><div className="relative pt-1 lg:pt-16"><div className="absolute -right-1 top-0 hidden h-24 w-24 border-l border-t border-[#111211]/30 lg:block" /><p className="max-w-[510px] font-display text-2xl leading-snug sm:text-4xl">Every LYWARO silhouette is shaped around movement, balance, and everyday expression.</p><p className="mt-8 max-w-[390px] text-sm leading-7 text-[#111211]/55">We make fewer decisions, more deliberately. The result is footwear that earns its place in the everyday rotation through clarity, not noise.</p><div className="mt-12 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.18em]"><span className="h-2 w-2 bg-[#D7F54A]" />LYWARO / 2026</div></div></div></div></section>

      {/* The Details */}
      <section className="bg-[#111211] px-5 py-24 text-[#EAE8E1] sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[0.6fr_1.4fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#D7F54A]">06 / The system</p><p className="mt-8 max-w-[220px] text-sm leading-6 text-white/45">A closer look at the decisions behind the silhouette.</p></div><div><div className="mb-8 flex items-end justify-between gap-6 border-b border-white/10 pb-5"><h2 className="font-display text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">The details.</h2><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/35">0{activeFeature + 1} / 04</span></div><div className="grid border-t border-white/10 sm:grid-cols-4">{features.map((feature, index) => <button key={feature} onClick={() => setActiveFeature(index)} className={`group border-b border-white/10 p-5 text-left transition sm:border-b-0 sm:border-r sm:last:border-r-0 ${index === activeFeature ? "bg-[#1B1E1B]" : "hover:bg-white/[0.03]"}`}><div className="flex items-center justify-between"><span className={`font-mono text-[9px] tracking-[0.18em] ${index === activeFeature ? "text-[#D7F54A]" : "text-white/35"}`}>0{index + 1}</span><Plus size={14} className={`transition ${index === activeFeature ? "rotate-45 text-[#D7F54A]" : "text-white/30"}`} /></div><h3 className="mt-20 font-display text-lg">{feature}</h3><p className={`mt-3 text-xs leading-5 transition ${index === activeFeature ? "text-white/60" : "text-white/30"}`}>{featureCopy[index]}</p></button>)}</div></div></div></div></section>

      {/* Movement CTA — editorial replaced with gradient */}
      <section className="relative min-h-[570px] overflow-hidden bg-[#181B18] text-[#EAE8E1]">
        <div className="absolute inset-0 bg-gradient-to-r from-[#2a3a2a] via-[#1a2a1a] to-[#111211]" />
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: "repeating-linear-gradient(-45deg, transparent, transparent 3px, rgba(215,245,74,0.05) 3px, rgba(215,245,74,0.05) 6px)" }} />
        <div className="absolute inset-0 bg-gradient-to-r from-[#111211] via-[#111211]/45 to-transparent" />
        <div className="relative mx-auto flex min-h-[570px] max-w-[1440px] items-end px-5 pb-14 sm:px-8 lg:px-12 lg:pb-20"><div><p className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#D7F54A]"><span className="h-px w-8 bg-[#D7F54A]" />07 / Movement study</p><h2 className="mt-5 max-w-[650px] font-display text-6xl font-semibold leading-[0.86] tracking-[-0.06em] sm:text-8xl">Make space<br />to move.</h2><Link href="/shop" className="mt-8 inline-flex items-center gap-3 border-b border-white/35 pb-2 font-mono text-[10px] uppercase tracking-[0.18em] transition hover:border-[#D7F54A] hover:text-[#D7F54A]">Enter the collection <ArrowUpRight size={14} /></Link></div></div>
      </section>

      {/* Footer */}
      <footer className="bg-[#EAE8E1] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-10 border-b border-[#111211]/15 pb-10 md:flex-row md:items-end"><div><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center border border-[#111211]"><img src="/lywaro-logo.svg" alt="LYWARO" className="h-5 w-5 object-contain" /></span><span className="font-display text-[15px] font-semibold tracking-[0.14em]">LYWΛRO</span></div><p className="mt-5 font-display text-2xl tracking-tight">Engineered to move.</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-3 font-mono text-[10px] uppercase tracking-[0.16em] text-[#111211]/55"><Link href="/shop" className="hover:text-[#111211]">Shop</Link><a href="#collection" className="hover:text-[#111211]">Collection</a><a href="#apex-story" className="hover:text-[#111211]">Apex</a><Link href="/shop" className="hover:text-[#111211]">Journal</Link></div><div className="max-w-[220px]"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#111211]/45">Dispatches</p><div className="mt-3 flex border-b border-[#111211]/25 py-2"><input aria-label="Email address" placeholder="Your email" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#111211]/40" /><button aria-label="Subscribe"><ChevronRight size={16} /></button></div></div></div><div className="flex flex-col justify-between gap-3 pt-5 font-mono text-[9px] uppercase tracking-[0.14em] text-[#111211]/40 sm:flex-row"><span>© 2026 LYWARO STUDIO</span><span>Precision / comfort / intent</span><span>Privacy · Terms</span></div></div></footer>
    </main>
    <CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} />
  </div>;
}
