// Blacktop Editorial: commerce stays catalog-like but uses offset plates, annotation rails, and intentional negative space.
import { useMemo, useState } from "react";
import { ArrowUpRight, ChevronDown, Filter, Search, SlidersHorizontal } from "lucide-react";
import { Link } from "wouter";
import ProductCard from "@/components/ProductCard";
import { CartDrawer, Header } from "@/components/StoreChrome";
import { useStore } from "@/contexts/StoreContext";

export default function Shop() {
  const { products } = useStore();
  const [cartOpen, setCartOpen] = useState(false);
  const [category, setCategory] = useState("All");
  const [color, setColor] = useState("All tones");
  const [sort, setSort] = useState("Featured");
  const [query, setQuery] = useState("");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const filtered = useMemo(() => {
    const result = products.filter((product) => {
      const matchesCategory = category === "All" || product.category.toLowerCase().includes(category.toLowerCase());
      const matchesColor = color === "All tones" || product.tone === color;
      const matchesQuery = `${product.name} ${product.category}`.toLowerCase().includes(query.toLowerCase());
      return matchesCategory && matchesColor && matchesQuery;
    });
    return [...result].sort((a, b) => sort === "Price: low" ? a.price - b.price : sort === "Price: high" ? b.price - a.price : a.id === "apex" ? -1 : b.id === "apex" ? 1 : 0);
  }, [category, color, query, sort, products]);

  return <div className="min-h-screen bg-[#EAE8E1] text-[#111211]"><Header onCart={() => setCartOpen(true)} /><main className="px-5 pb-24 pt-32 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 border-b border-[#111211]/15 pb-12 lg:grid-cols-[0.5fr_1.5fr]"><div className="relative"><span className="absolute -left-5 top-0 hidden h-24 w-px bg-[#D7F54A] lg:block" /><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#111211]/45">LYWARO / Catalog</p><h1 className="mt-6 max-w-[540px] font-display text-6xl font-semibold leading-[0.84] tracking-[-0.07em] sm:text-8xl">The<br /><span className="text-[#111211]/35">collection.</span></h1></div><div className="grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><p className="max-w-[410px] font-display text-2xl leading-snug">Four silhouettes built around the distance between intention and movement.</p><p className="mt-5 max-w-[350px] text-sm leading-6 text-[#111211]/55">Find the one that fits your everyday. Each piece is made to be returned to.</p></div><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#111211]/45">{filtered.length} / {products.length} styles</div></div></div>
      <div className="flex flex-col gap-4 border-b border-[#111211]/15 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-2 overflow-x-auto"><button onClick={() => setFiltersOpen((value) => !value)} className="mr-2 inline-flex shrink-0 items-center gap-2 border border-[#111211]/20 px-3 py-2 font-mono text-[10px] uppercase tracking-[0.15em] lg:hidden"><SlidersHorizontal size={13} /> Filters</button>{["All", "Run", "Move", "Form"].map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 px-3 py-2 font-mono text-[10px] uppercase tracking-[0.15em] transition ${category === item ? "bg-[#111211] text-[#EAE8E1]" : "text-[#111211]/50 hover:text-[#111211]"}`}>{item}</button>)}</div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="flex items-center gap-2 border-b border-[#111211]/20 pb-2"><Search size={14} className="text-[#111211]/45" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the collection" className="w-full bg-transparent text-sm outline-none placeholder:text-[#111211]/40 sm:w-48" /></label><label className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.12em] text-[#111211]/55">Sort <select value={sort} onChange={(event) => setSort(event.target.value)} className="bg-transparent py-2 text-[#111211] outline-none"><option>Featured</option><option>Price: low</option><option>Price: high</option></select><ChevronDown size={12} /></label></div></div>
      <div className={`${filtersOpen ? "grid" : "hidden"} grid-cols-1 gap-4 border-b border-[#111211]/15 py-5 sm:grid-cols-3 lg:hidden`}><label className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.14em]">Color<select value={color} onChange={(event) => setColor(event.target.value)} className="bg-transparent text-right outline-none"><option>All tones</option><option value="carbon">Carbon</option><option value="bone">Bone</option><option value="smoke">Smoke</option><option value="black">Black</option></select></label><label className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.14em]">Size<select className="bg-transparent text-right outline-none"><option>All sizes</option><option>08</option><option>09</option><option>10</option><option>11</option></select></label><label className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.14em]">Price<select className="bg-transparent text-right outline-none"><option>Any price</option><option>Under $175</option><option>$175+</option></select></label></div>
      <div className="mt-12 grid gap-x-6 gap-y-16 lg:grid-cols-4"><div className="hidden border-r border-[#111211]/15 pr-5 lg:col-span-1 lg:block"><div className="sticky top-28 space-y-9"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em]">01 / Filters</p><p className="mt-4 text-sm leading-6 text-[#111211]/55">Use the catalog as a starting point. The rest is a matter of fit.</p></div><div className="space-y-4 border-t border-[#111211]/15 pt-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#111211]/45">Color</p>{["All tones", "carbon", "bone", "smoke", "black"].map((item) => <button key={item} onClick={() => setColor(item)} className={`block font-mono text-[10px] uppercase tracking-[0.14em] ${color === item ? "text-[#111211] underline underline-offset-4" : "text-[#111211]/40 hover:text-[#111211]"}`}>{item}</button>)}</div><div className="border-t border-[#111211]/15 pt-4"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#111211]/45">Registration</p><div className="mt-5 h-px w-full bg-[#111211]/10"><div className="h-full w-1/2 bg-[#D7F54A]" /></div><p className="mt-3 font-mono text-[9px] uppercase tracking-[0.14em] text-[#111211]/35">Price range / $145—$210</p></div><Link href="/" className="inline-flex items-center gap-2 border-b border-[#111211]/35 pb-1 font-mono text-[10px] uppercase tracking-[0.16em]">Back to studio <ArrowUpRight size={12} /></Link></div></div><div className="grid grid-cols-1 gap-x-6 gap-y-16 sm:grid-cols-2 lg:col-span-3 lg:grid-cols-3">{filtered.length > 0 ? filtered.map((product) => <div key={product.id} className={product.id === "apex" ? "sm:col-span-2 lg:col-span-2" : ""}><ProductCard product={product} /></div>) : <div className="col-span-full border border-dashed border-[#111211]/20 py-24 text-center"><Filter className="mx-auto text-[#111211]/35" /><p className="mt-5 font-display text-2xl">No matching styles.</p><button onClick={() => { setCategory("All"); setColor("All tones"); setQuery(""); }} className="mt-5 border-b border-[#111211] pb-1 font-mono text-[10px] uppercase tracking-[0.16em]">Reset filters</button></div>}</div></div></div></main><CartDrawer open={cartOpen} onClose={() => setCartOpen(false)} /></div>;
}
